# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- script: | 
    dotnet restore LoanApproval.sln
    ls
  displayName: 'dotnet restore'


- script: | 
    dotnet build LoanApproval.sln
    ls
    cd /home/vsts/work/1/s/LoanApproval/bin/Debug/netcoreapp2.1/
    ls -al
    pwd
  displayName: 'dotnet build'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '/home/vsts/work/1/s/LoanApproval/bin/Debug/netcoreapp2.1'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: LambdaDeployFunction@1
  inputs:
    awsCredentials: 'awsconnection'
    regionName: 'ap-south-1'
    deploymentMode: 'codeandconfiguration'
    functionName: 'LoanApproval'
    functionHandler: 'LoanApproval::LoanApproval.LambdaEntryPoint::FunctionHandlerAsync'
    runtime: 'dotnetcore2.1'
    codeLocation: 'localfile'
    localZipFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    roleARN: 'arn:aws:iam::618393550001:role/azure-lambda-role'
    environment: |
      Database=ApplicationSubmission
      Port=3306
      PWD=admin8910
      Server=applicationsubmission.cikv7fwlsku8.ap-south-1.rds.amazonaws.com
      UID=admin


